"""
This type stub file was generated by pyright.
"""

from functools import lru_cache
from sqlalchemy.engine import Engine
from recipe_database.typing_ import str_or_URL

@lru_cache
def create_engine(url: str_or_URL) -> Engine:
    """It creates a SQL engine connected to the database at the given URL

    All created engines are stored in a cache for future re-use
    """
    ...

def create_database_and_tables(engine: Engine) -> None:
    """It creates database and tables for the recipe index given the SQL engine

    They are created only if they do not already exist.
    """
    ...

